sonar.host.url=https://sonarcloud.io
# Ganti dengan Organization Key dari SonarCloud Anda (lihat di pojok kiri atas dashboard SonarCloud)
sonar.projectKey=ricky.metal09_tambora-frontend
sonar.organization=ricky-metal09

sonar.projectName=Tambora Web App
sonar.projectVersion=1.0.0

sonar.sources=components,pages,composables,stores,utils,config
sonar.tests=test
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=node_modules/**,.nuxt/**,dist/**,coverage/**,*.config.*,types/**
sonar.coverage.exclusions=**/transaksi/**,app.vue,server/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
