import type { FormSectionConfig } from "~/types";

export const driverFormSections: FormSectionConfig[] = [
  {
    fields: [
      {
        key: "full_name",
        label: "Nama Pengemudi",
        type: "text",
        placeholder: "Nama pengemudi...",
        colSpan: 6,
        required: true,
      },
      {
        key: "phone_number",
        label: "No. Telepon",
        type: "phone",
        placeholder: "+6281234567890",
        colSpan: 6,
        required: false,
      },
      {
        key: "nik",
        label: "NIK",
        type: "text",
        placeholder: "16 digit NIK",
        colSpan: 6,
        required: false,
      },
      {
        key: "license_number",
        label: "Nomor SIM",
        type: "text",
        placeholder: "Nomor SIM...",
        colSpan: 6,
        required: false,
      },
      {
        key: "license_type",
        label: "Jenis SIM",
        type: "select",
        placeholder: "Pilih Jenis SIM",
        options: [
          { label: "SIM A", value: "SIM A" },
          { label: "SIM B1", value: "SIM B1" },
          { label: "SIM B2", value: "SIM B2" },
          { label: "SIM C", value: "SIM C" },
        ],
        colSpan: 6,
        required: false,
      },
      {
        key: "employment_status",
        label: "Status",
        type: "select",
        placeholder: "Pilih Status",
        options: [
          { label: "Aktif", value: "Aktif" },
          { label: "Cuti", value: "Cuti" },
          { label: "Non-Aktif", value: "Non-Aktif" },
        ],
        colSpan: 6,
        required: false,
      },
      {
        key: "birth_place",
        label: "Tempat Lahir",
        type: "text",
        placeholder: "Contoh: Bima / Mataram",
        colSpan: 6,
        required: false,
      },
      {
        key: "birth_date",
        label: "Tanggal Lahir",
        type: "date",
        placeholder: "Pilih Tanggal Lahir",
        colSpan: 6,
        required: false,
      },
      {
        key: "employment_start_date",
        label: "Tanggal Mulai",
        type: "date",
        placeholder: "Pilih Tanggal Mulai",
        colSpan: 6,
        required: false,
      },
      {
        key: "address",
        label: "Alamat",
        type: "textarea",
        placeholder: "Alamat...",
        colSpan: 12,
        required: false,
      },
      {
        key: "description",
        label: "Catatan",
        type: "textarea",
        placeholder: "Catatan...",
        colSpan: 12,
        required: false,
      },
    ],
  },
];
