import type { FormSectionConfig } from "~/types";

export const sentralFormSections: FormSectionConfig[] = [
  {
    title: "1. Identitas Sentral Pembangkit",
    fields: [
      {
        key: "nama_sentral",
        label: "Nama Sentral",
        type: "text",
        placeholder: "Contoh: PLTD Bitung",
        colSpan: 6,
        required: true,
      },
      {
        key: "kode_sentral",
        label: "Kode Sentral",
        type: "text",
        placeholder: "Contoh: PLTD-BTG",
        colSpan: 6,
        required: true,
      },
      {
        key: "kode_singkatan_sentral",
        label: "Singkatan Sentral",
        type: "text",
        placeholder: "Contoh: BTG",
        colSpan: 4,
        required: false,
      },
      {
        key: "kode_jenis_pembangkit",
        label: "Jenis Pembangkit",
        type: "select",
        placeholder: "Pilih Jenis",
        options: [
          { label: "PLTD (Diesel)", value: "PLTD" },
          { label: "PLTU (Uap / Batubara)", value: "PLTU" },
          { label: "PLTG (Gas)", value: "PLTG" },
          { label: "PLTMG (Mesin Gas)", value: "PLTMG" },
          { label: "PLTA (Air)", value: "PLTA" },
          { label: "PLTM / PLTMH (Mini/Mikrohidro)", value: "PLTM" },
          { label: "PLTP (Panas Bumi)", value: "PLTP" },
          { label: "PLTS (Surya)", value: "PLTS" },
          { label: "PLTB (Bayu/Angin)", value: "PLTB" },
          { label: "PLTBm (Biomassa)", value: "PLTBm" },
          { label: "PLTGU (Gas & Uap)", value: "PLTGU" },
        ],
        colSpan: 4,
        required: false,
      },
      {
        key: "jenis_bahan_bakar",
        label: "Jenis Bahan Bakar Utama",
        type: "select",
        placeholder: "Pilih BBM",
        options: [
          { label: "HSD (High Speed Diesel)", value: "HSD" },
          { label: "B30 / B35 (Biodiesel)", value: "B30" },
          { label: "MFO (Marine Fuel Oil)", value: "MFO" },
          { label: "Batubara (Coal)", value: "Batubara" },
          { label: "Gas Alam (Natural Gas)", value: "Gas" },
          { label: "Biomassa", value: "Biomassa" },
          { label: "Air (Hydro)", value: "Air" },
          { label: "Surya (Solar)", value: "Surya" },
          { label: "Geothermal", value: "Geothermal" },
        ],
        colSpan: 4,
        required: false,
      },
      {
        key: "daya_terpasang",
        label: "Daya Terpasang (kW)",
        type: "number",
        placeholder: "Contoh: 15000",
        colSpan: 4,
        required: false,
      },
      {
        key: "daya_mampu",
        label: "Daya Mampu (kW)",
        type: "number",
        placeholder: "Contoh: 14000",
        colSpan: 4,
        required: false,
      },
      {
        key: "kondisi",
        label: "Kondisi Operasi",
        type: "select",
        placeholder: "Pilih Kondisi",
        options: [
          { label: "Siap Operasi", value: "SIAP_OPERASI" },
          { label: "Standby", value: "STANDBY" },
          { label: "Pemeliharaan", value: "PEMELIHARAAN" },
          { label: "Gangguan", value: "GANGGUAN" },
          { label: "Rusak Berat", value: "RUSAK_BERAT" },
        ],
        colSpan: 4,
        required: false,
      },
    ],
  },
  {
    title: "2. Lokasi Geografis & Spasial",
    fields: [
      {
        key: "latitude",
        label: "Latitude",
        type: "number",
        placeholder: "Contoh: 1.44",
        colSpan: 3,
        required: false,
      },
      {
        key: "longitude",
        label: "Longitude",
        type: "number",
        placeholder: "Contoh: 125.18",
        colSpan: 3,
        required: false,
      },
      {
        key: "radius",
        label: "Radius Area (meter)",
        type: "number",
        placeholder: "Contoh: 500",
        colSpan: 3,
        required: false,
      },
      {
        key: "color",
        label: "Warna Marker GIS",
        type: "text",
        placeholder: "Contoh: #FF5733",
        colSpan: 3,
        required: false,
      },
      {
        key: "provinsi",
        label: "Provinsi",
        type: "text",
        placeholder: "Contoh: Sulawesi Utara",
        colSpan: 4,
        required: false,
      },
      {
        key: "kota_kabupaten",
        label: "Kota / Kabupaten",
        type: "text",
        placeholder: "Contoh: Kota Bitung",
        colSpan: 4,
        required: false,
      },
      {
        key: "kecamatan",
        label: "Kecamatan",
        type: "text",
        placeholder: "Contoh: Madidir",
        colSpan: 4,
        required: false,
      },
      {
        key: "kelurahan",
        label: "Kelurahan / Desa",
        type: "text",
        placeholder: "Contoh: Pakadoodan",
        colSpan: 6,
        required: false,
      },
      {
        key: "nama_pulau",
        label: "Nama Pulau",
        type: "text",
        placeholder: "Contoh: Sulawesi",
        colSpan: 6,
        required: false,
      },
      {
        key: "alamat",
        label: "Alamat Lengkap",
        type: "textarea",
        placeholder: "Masukkan alamat lengkap lokasi sentral pembangkit",
        colSpan: 12,
        required: false,
      },
    ],
  },
  {
    title: "3. Kepemilikan & Manajemen Operasional",
    fields: [
      {
        key: "pengelola",
        label: "Instansi Pengelola",
        type: "text",
        placeholder: "Contoh: PLN Indonesia Power",
        colSpan: 6,
        required: false,
      },
      {
        key: "status_milik",
        label: "Status Kepemilikan",
        type: "select",
        placeholder: "Pilih Status",
        options: [
          { label: "PLN (Milik Sendiri)", value: "PLN" },
          { label: "IPP (Independent Power Producer)", value: "IPP" },
          { label: "Sewa (Rental)", value: "SEWA" },
          { label: "KSO (Kerja Sama Operasi)", value: "KSO" },
        ],
        colSpan: 6,
        required: false,
      },
      {
        key: "tahun_operasi",
        label: "Tahun Mulai Operasi (COD)",
        type: "number",
        placeholder: "Contoh: 2015",
        colSpan: 4,
        required: false,
      },
      {
        key: "nilai_asset_awal",
        label: "Nilai Aset Awal (Rp)",
        type: "number",
        placeholder: "Contoh: 50000000000",
        colSpan: 4,
        required: false,
      },
      {
        key: "pemegang_saham",
        label: "Pemegang Saham / Mitra",
        type: "text",
        placeholder: "Contoh: PT PLN (Persero)",
        colSpan: 4,
        required: false,
      },
      {
        key: "manager",
        label: "Nama Manager Sentral",
        type: "text",
        placeholder: "Contoh: Budi Santoso",
        colSpan: 6,
        required: false,
      },
      {
        key: "manager_phone",
        label: "No. HP Manager",
        type: "phone",
        placeholder: "+6281234567890",
        colSpan: 6,
        required: false,
      },
      {
        key: "wakil_manager",
        label: "Nama Wakil Manager / Asman",
        type: "text",
        placeholder: "Contoh: Ahmad Fauzi",
        colSpan: 6,
        required: false,
      },
      {
        key: "wakil_manager_phone",
        label: "No. HP Wakil Manager",
        type: "phone",
        placeholder: "+6281298765432",
        colSpan: 6,
        required: false,
      },
      {
        key: "sejarah",
        label: "Sejarah Ringkas Unit",
        type: "textarea",
        placeholder: "Sejarah pendirian dan commissioning sentral",
        colSpan: 12,
        required: false,
      },
      {
        key: "keterangan",
        label: "Catatan Tambahan",
        type: "textarea",
        placeholder: "Informasi operasional penting lainnya",
        colSpan: 12,
        required: false,
      },
    ],
  },
];
