import type { FormSectionConfig } from "~/types";

export interface SentralSchemaOptions {
  regionalOptions?: { label: string; value: any }[];
  rantingOptions?: { label: string; value: any }[];
  systemOptions?: { label: string; value: any }[];
  hasSelectedRegional?: boolean;
}

export const getSentralFormSections = (
  options: SentralSchemaOptions = {},
): FormSectionConfig[] => {
  const regionalOptions = options.regionalOptions || [];
  const rantingOptions = options.rantingOptions || [];
  const systemOptions = options.systemOptions || [];

  return [
    {
      title: "1. Identitas & Wilayah Sentral",
      fields: [
        {
          key: "kode_sentral",
          label: "Kode",
          type: "text",
          placeholder: "Contoh: PLTD-BTG",
          required: true,
          colSpan: 6,
        },
        {
          key: "nama_sentral",
          label: "Nama",
          type: "text",
          placeholder: "Contoh: PLTD Bitung",
          required: true,
          colSpan: 6,
        },
        {
          key: "kode_singkatan_sentral",
          label: "Singkatan Sentral",
          type: "text",
          placeholder: "Contoh: BTG",
          required: false,
          colSpan: 6,
        },
        {
          key: "kode_jenis_pembangkit",
          label: "Jenis Pembangkit",
          type: "select",
          placeholder: "Pilih Jenis Pembangkit",
          options: [
            { label: "PLTD (Diesel)", value: "PLTD" },
            { label: "PLTU (Uap / Batubara)", value: "PLTU" },
            { label: "PLTG (Gas)", value: "PLTG" },
            { label: "PLTMG (Mesin Gas)", value: "PLTMG" },
            { label: "PLTA (Air)", value: "PLTA" },
            { label: "PLTM / PLTMH (Minihidro)", value: "PLTM" },
            { label: "PLTP (Panas Bumi)", value: "PLTP" },
            { label: "PLTS (Surya)", value: "PLTS" },
            { label: "PLTB (Bayu/Angin)", value: "PLTB" },
            { label: "PLTBm (Biomassa)", value: "PLTBm" },
            { label: "PLTGU (Gas & Uap)", value: "PLTGU" },
          ],
          required: false,
          colSpan: 6,
        },
        {
          key: "jenis_bahan_bakar",
          label: "Bahan Bakar Utama",
          type: "select",
          placeholder: "Pilih Bahan Bakar",
          options: [
            { label: "HSD (High Speed Diesel)", value: "HSD" },
            { label: "B30 / B35 (Biodiesel)", value: "B30" },
            { label: "MFO (Marine Fuel Oil)", value: "MFO" },
            { label: "Batubara (Coal)", value: "Batubara" },
            { label: "Gas Alam (Natural Gas)", value: "Gas" },
            { label: "Biomassa", value: "Biomassa" },
            { label: "Air (Hydro)", value: "Air" },
            { label: "Surya (Solar)", value: "Surya" },
            { label: "Geothermal", value: "Geothermal" },
          ],
          required: false,
          colSpan: 6,
        },
        {
          key: "kode_wilayah",
          label: "Regional",
          type: "select",
          placeholder: "Pilih Regional",
          options: regionalOptions,
          required: false,
          colSpan: 6,
        },
        {
          key: "kode_ranting",
          label: "Ranting",
          type: "select",
          placeholder: options.hasSelectedRegional
            ? rantingOptions.length > 0
              ? "Pilih Ranting"
              : "Tidak Ada Ranting di Regional Ini"
            : "Pilih Regional Terlebih Dahulu",
          options: rantingOptions,
          disabled: (form: Record<string, any>) => !form.kode_wilayah,
          required: false,
          colSpan: 6,
        },
        {
          key: "kode_sistem",
          label: "Sistem",
          type: systemOptions.length > 0 ? "select" : "text",
          placeholder: "Pilih / Input Sistem",
          options: systemOptions.length > 0 ? systemOptions : undefined,
          required: false,
          colSpan: 6,
        },
      ],
    },
    {
      title: "2. Kapasitas & Kondisi Operasi",
      fields: [
        {
          key: "daya_terpasang",
          label: "Daya Terpasang (kW)",
          type: "number",
          placeholder: "Contoh: 15000",
          required: false,
          colSpan: 6,
        },
        {
          key: "daya_mampu",
          label: "Daya Mampu (kW)",
          type: "number",
          placeholder: "Contoh: 14000",
          required: false,
          colSpan: 6,
        },
        {
          key: "kondisi",
          label: "Kondisi Operasi",
          type: "select",
          placeholder: "Pilih Kondisi",
          options: [
            { label: "Siap Operasi", value: "SIAP_OPERASI" },
            { label: "Standby", value: "STANDBY" },
            { label: "Pemeliharaan", value: "PEMELIHARAAN" },
            { label: "Gangguan", value: "GANGGUAN" },
            { label: "Rusak Berat", value: "RUSAK_BERAT" },
          ],
          required: false,
          colSpan: 6,
        },
        {
          key: "tahun_operasi",
          label: "Tahun Operasi",
          type: "number",
          placeholder: "Contoh: 2015",
          required: false,
          colSpan: 6,
        },
        {
          key: "approve_status",
          label: "Status Approval",
          type: "select",
          placeholder: "Pilih Status Approval",
          options: [
            { label: "DRAFT", value: "DRAFT" },
            { label: "APPROVED", value: "APPROVED" },
            { label: "REJECTED", value: "REJECTED" },
          ],
          required: false,
          colSpan: 6,
        },
        {
          key: "color",
          label: "Warna Marker Peta",
          type: "color",
          placeholder: "#FF5733",
          required: false,
          colSpan: 6,
        },
      ],
    },
    {
      title: "3. Kepemilikan & Pengelolaan Aset",
      fields: [
        {
          key: "status_milik",
          label: "Status Milik",
          type: "select",
          placeholder: "Pilih Status Milik",
          options: [
            { label: "PLN", value: "PLN" },
            { label: "SEWA", value: "SEWA" },
            { label: "IPP", value: "IPP" },
            { label: "KERJASAMA", value: "KERJASAMA" },
          ],
          required: false,
          colSpan: 6,
        },
        {
          key: "kode_status_milik",
          label: "Kode Status Milik",
          type: "select",
          placeholder: "Pilih Kode Status Milik",
          options: [
            { label: "Milik Sendiri", value: "MILIK_SENDIRI" },
            { label: "Sewa", value: "SEWA" },
            { label: "IPP", value: "IPP" },
            { label: "Kerjasama", value: "KERJASAMA" },
          ],
          required: false,
          colSpan: 6,
        },
        {
          key: "status_milik_detail",
          label: "Detail Status Milik",
          type: "text",
          placeholder: "Contoh: Aset Tetap PLN",
          required: false,
          colSpan: 6,
        },
        {
          key: "pengelola",
          label: "Pengelola",
          type: "text",
          placeholder: "Contoh: PLN Indonesia Power",
          required: false,
          colSpan: 6,
        },
        {
          key: "pemegang_saham",
          label: "Pemegang Saham",
          type: "text",
          placeholder: "Contoh: PT PLN (Persero)",
          required: false,
          colSpan: 6,
        },
        {
          key: "nilai_asset_awal",
          label: "Nilai Aset Awal (Rp)",
          type: "number",
          placeholder: "Contoh: 50000000000",
          required: false,
          colSpan: 6,
        },
      ],
    },
    {
      title: "4. Lokasi & Geografis",
      fields: [
        {
          key: "provinsi",
          label: "Provinsi",
          type: "text",
          placeholder: "Contoh: Sulawesi Utara",
          required: false,
          colSpan: 6,
        },
        {
          key: "kota_kabupaten",
          label: "Kota / Kabupaten",
          type: "text",
          placeholder: "Contoh: Kota Bitung",
          required: false,
          colSpan: 6,
        },
        {
          key: "kecamatan",
          label: "Kecamatan",
          type: "text",
          placeholder: "Contoh: Madidir",
          required: false,
          colSpan: 6,
        },
        {
          key: "kelurahan",
          label: "Kelurahan",
          type: "text",
          placeholder: "Contoh: Pakadoodan",
          required: false,
          colSpan: 6,
        },
        {
          key: "nama_pulau",
          label: "Nama Pulau",
          type: "text",
          placeholder: "Contoh: Sulawesi",
          required: false,
          colSpan: 6,
        },
        {
          key: "radius",
          label: "Radius Area (Meter)",
          type: "number",
          placeholder: "Contoh: 500",
          required: false,
          colSpan: 6,
        },
        {
          key: "alamat",
          label: "Alamat Lengkap",
          type: "textarea",
          placeholder: "Contoh: Jl. Pelabuhan Samudera Bitung",
          required: false,
          colSpan: 12,
          rows: 2,
        },
        {
          key: "coordinates",
          label: "",
          type: "coordinate-picker",
          latKey: "latitude",
          lngKey: "longitude",
          required: false,
          colSpan: 12,
        },
      ],
    },
    {
      title: "5. Manajemen & Kontak Person",
      fields: [
        {
          key: "manager",
          label: "Nama Manager",
          type: "text",
          placeholder: "Contoh: Budi Santoso",
          required: false,
          colSpan: 6,
        },
        {
          key: "manager_phone",
          label: "No. Telepon / HP Manager",
          type: "phone",
          placeholder: "Contoh: 81234567890",
          required: false,
          colSpan: 6,
        },
        {
          key: "wakil_manager",
          label: "Nama Wakil Manager",
          type: "text",
          placeholder: "Contoh: Ahmad Fauzi",
          required: false,
          colSpan: 6,
        },
        {
          key: "wakil_manager_phone",
          label: "No. Telepon / HP Wakil Manager",
          type: "phone",
          placeholder: "Contoh: 81298765432",
          required: false,
          colSpan: 6,
        },
      ],
    },
    {
      title: "6. Informasi Tambahan & Riwayat",
      fields: [
        {
          key: "photo",
          label: "URL Foto Sentral",
          type: "text",
          placeholder: "Contoh: https://example.com/photo-bitung.jpg",
          required: false,
          colSpan: 12,
        },
        {
          key: "sejarah",
          label: "Sejarah Operasi",
          type: "textarea",
          placeholder:
            "Contoh: Beroperasi sejak tahun 2015 untuk suplai Pelabuhan Bitung",
          required: false,
          colSpan: 12,
          rows: 2,
        },
        {
          key: "penghargaan",
          label: "Penghargaan",
          type: "textarea",
          placeholder: "Contoh: Zero Accident Award 2023",
          required: false,
          colSpan: 12,
          rows: 2,
        },
        {
          key: "deskripsi",
          label: "Deskripsi",
          type: "textarea",
          placeholder: "Contoh: Pembangkit Listrik Tenaga Diesel Bitung",
          required: false,
          colSpan: 12,
          rows: 2,
        },
        {
          key: "keterangan",
          label: "Keterangan",
          type: "textarea",
          placeholder: "Contoh: Unit pembangkit utama Bitung",
          required: false,
          colSpan: 12,
          rows: 2,
        },
      ],
    },
  ];
};

export const sentralFormSections: FormSectionConfig[] =
  getSentralFormSections();
